services:
  postgres:
    label: PostgreSQL
    engine: postgres
    available: true
    provision_on: create_database
  mysql:
    label: MySQL
    engine: mysql
    available: false
    provision_on: create_database
  centrifugo:
    label: Realtime
    engine: centrifugo
    available: true
    provision_on: user_enable
  minio:
    label: Storage
    engine: minio
    available: false
    provision_on: user_enable
  redis:
    label: Redis Queue
    engine: redis
    available: true
    provision_on: org_enable_queue
  rabbitmq:
    label: RabbitMQ
    engine: rabbitmq
    available: false
    provision_on: org_enable_queue
